# Generated by Django 4.2.5 on 2023-10-04 08:51

import uuid

import django.utils.timezone
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("datetime_created", models.DateTimeField(auto_now_add=True, verbose_name="Время создания")),
                ("datetime_updated", models.DateTimeField(auto_now=True, verbose_name="Время обновления")),
                ("title", models.CharField(max_length=250, verbose_name="Заголовок")),
                ("slug", models.SlugField(max_length=250, unique=True, verbose_name="Слаг")),
                ("description", models.TextField(verbose_name="Описание")),
                ("seo_description", models.CharField(blank=True, max_length=100, verbose_name="Описание для СЕО")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
                "db_table": "tag",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("datetime_created", models.DateTimeField(auto_now_add=True, verbose_name="Время создания")),
                ("datetime_updated", models.DateTimeField(auto_now=True, verbose_name="Время обновления")),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True, verbose_name="Слаг")),
                ("title", models.CharField(max_length=250, verbose_name="Заголовок")),
                ("seo_title", models.CharField(max_length=250, verbose_name="СЕО заголовок")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subcategories",
                        to="core.category",
                        verbose_name="Родительская категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                ("datetime_created", models.DateTimeField(auto_now_add=True, verbose_name="Время создания")),
                ("datetime_updated", models.DateTimeField(auto_now=True, verbose_name="Время обновления")),
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                ("content", tinymce.models.HTMLField()),
                ("slug", models.SlugField(max_length=250, unique=True, verbose_name="Слаг")),
                ("image", models.ImageField(max_length=1000, upload_to="content/", verbose_name="Изображение")),
                (
                    "published_date",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Дата публикации"),
                ),
                ("view_count", models.IntegerField(default=0, verbose_name="Количество просмотров")),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="category_article", to="core.category", verbose_name="Категории"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_articles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(blank=True, related_name="tag_article", to="core.tag", verbose_name="Теги"),
                ),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
                "db_table": "article",
                "ordering": ("-datetime_created", "-published_date"),
            },
        ),
        migrations.CreateModel(
            name="PinnedArticle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("datetime_created", models.DateTimeField(auto_now_add=True, verbose_name="Время создания")),
                ("datetime_updated", models.DateTimeField(auto_now=True, verbose_name="Время обновления")),
                ("order", models.IntegerField(verbose_name="Позиция")),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.article",
                        verbose_name="Новость",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фиксированная новость",
                "verbose_name_plural": "Фиксированные новости",
                "ordering": ("order",),
                "indexes": [models.Index(fields=["order"], name="core_pinned_order_8f8a85_idx")],
            },
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["id"], name="category_id_db0083_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["view_count", "published_date", "datetime_created"], name="article_view_co_6b9c7a_idx"
            ),
        ),
    ]
